scheme("TabletBasic")
project("TabletBasic.xcodeproj")

devices([
  "iPhone 17 Pro Max",
  "iPad Pro 13-inch (M4)"
])

languages([
  "en-US"
])

output_directory("./fastlane/screenshots")
clear_previous_screenshots(false)
reinstall_app(true)
