scheme("TabletBasic")
project("TabletBasic.xcodeproj")

devices([
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US"
])

output_directory("./fastlane/screenshots")
clear_previous_screenshots(false)
reinstall_app(true)
